CREATE DATABASE chu
go

CREATE TABLE Cadre (
idCa INT PRIMARY KEY,
intituleAr VARCHAR(100) COLLATE Arabic_100_CS_AS_KS_WS_SC,
intituleFr VARCHAR(100)
) 
go

CREATE TABLE Corps (
idCr INT PRIMARY KEY,
intituleAr VARCHAR(100) COLLATE Arabic_100_CS_AS_KS_WS_SC,
intituleFr VARCHAR(100)
) 
go

CREATE TABLE Grade (
idG INT PRIMARY KEY,
intituleAr VARCHAR(100) COLLATE Arabic_100_CS_AS_KS_WS_SC,
intituleFr VARCHAR(100)
)
go

CREATE TABLE Specialite (
idS INT PRIMARY KEY,
intituleAr VARCHAR(100) COLLATE Arabic_100_CS_AS_KS_WS_SC,
intituleFr VARCHAR(100)
) 
go

CREATE TABLE Interne (
cin  VARCHAR(100) PRIMARY KEY,
nomCompletFr VARCHAR(100),
dateN VARCHAR(100),
sexe VARCHAR(100),
dateArr VARCHAR(100),
budget VARCHAR(100),
observation VARCHAR(100),
dateRecru VARCHAR(100),
stage1 VARCHAR(255),
stage2 VARCHAR(255),
stage3 VARCHAR(255),
stage4 VARCHAR(255)
) 
go

CREATE TABLE Hopital (
idH INT PRIMARY KEY,
intituleAr VARCHAR(100) COLLATE Arabic_100_CS_AS_KS_WS_SC,
intituleFr VARCHAR(100)
) 
go

CREATE TABLE Service (
idSe INT PRIMARY KEY,
intituleAr VARCHAR(100) COLLATE Arabic_100_CS_AS_KS_WS_SC,
intituleFr VARCHAR(100),
fk_idHopital INT,

CONSTRAINT  fk_hopital FOREIGN KEY (fk_idHopital) REFERENCES Hopital(idH)
) 
go