package org.chu.greve.util;

public abstract class Nationalite {

	static public String[] getNationalite() {
		String list[] = { "AFGHANE", "ALGERIENNE", "AMERICAINE", "APATRIDE", "BELGE", "BOLIVIENNE", "BRITANIQUE",
				"BULGARE", "CAMEROUNAISE", "CANADIENNE", "CHILIENNE", "CHINOISE", "CUBAINE", "EGYPTIENNE", "ESPAGNOLE",
				"ETHIOPIENNE", "FINLANDAISE", "FRANCAISE", "GREQUE", "GUINEENNE", "HAITIENNE", "HOLLANDAISE",
				"HONGROISE", "INDIENNE", "IRAKIENNE", "IRLANDAISE", "ITALIENNE", "JAPONAISE", "JORDANIENNE",
				"LIBANAISE", "MALIENNE", "MAROCAINE", "MAURITANIENNE", "NIGERIENNE (NIGER)", "PAKISTANAISE",
				"PALISTINIENNE", "POLONAISE", "PORTUGAISE", "RDA", "RFA", "ROUMAINE", "RUSSE", "SENEGALAISE",
				"SOUDANAISE", "SUEDOISE", "SUISSE", "SYRIENNE", "TCHECOSLOVAQUE", "THAILLANDAISE", "TUNISIENNE",
				"TURQUE", "URUGUAYENNE", "VIETNAMIENNE", "YOUGOSLAVE" };
		return list;
	}

}
